def javaServices = [

    "api-gateway",
    "appointment-service",
    "auth-service",
    "billing-service",
    "doctor-service",
    "medical-record-service",
    "patient-service"

]

def pythonService = "notification-service"



pipeline {


    agent any



    tools {

        jdk 'JDK21'

        maven 'Maven'

    }



    environment {


        AWS_REGION = "ap-south-1"

        AWS_ACCOUNT_ID = "897355252117"

        ECR_REGISTRY = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"

        IMAGE_TAG = "${BUILD_NUMBER}"

        HELM_RELEASE = "hospital-management"

        HELM_CHART = "helm/hospital-management"


    }





    stages {



        stage('Checkout Code') {


            steps {


                git(

                    branch: 'main',

                    credentialsId: 'github-creds',

                    url: 'https://github.com/kiruthigagokul/hospital-management.git'

                )


            }


        }





        stage('Verify Tools') {


            steps {


                sh '''

                java -version

                mvn -version

                docker --version

                python3 --version

                kubectl version --client

                helm version

                aws --version


                '''


            }


        }







        stage('Build Java Services') {


            steps {


                script {


                    javaServices.each { service ->


                        dir("hospital_management_app/${service}") {


                            sh '''

                            echo "Building Java service"

                            mvn clean package -DskipTests


                            '''


                        }


                    }


                }


            }


        }








        stage('Build Python Service') {


            steps {


                dir("hospital_management_app/${pythonService}") {


                    sh '''


                    echo "Creating Python environment"


                    python3 -m venv venv


                    . venv/bin/activate


                    pip install --upgrade pip


                    pip install -r requirements.txt


                    '''


                }


            }


        }








        stage('Run Tests') {


            steps {


                script {


                    javaServices.each { service ->



                        dir("hospital_management_app/${service}") {



                            sh '''

                            mvn test


                            '''

                        }


                    }






                    dir("hospital_management_app/${pythonService}") {



                        sh '''


                        . venv/bin/activate



                        if [ -d tests ]; then


                            pytest --junitxml=test-results.xml


                        else


                            echo "No Python tests found"


                        fi



                        '''



                    }



                }



            }



        }








        stage('Publish Test Reports') {


            steps {


                junit allowEmptyResults: true,

                testResults: '**/target/surefire-reports/*.xml'



                junit allowEmptyResults: true,

                testResults: '**/test-results.xml'


            }


        }








        stage('SonarQube Analysis') {

    steps {

        withSonarQubeEnv('SonarQube') {

            script {

                javaServices.each { service ->

                    dir("hospital_management_app/${service}") {

                        sh """
                            mvn org.sonarsource.scanner.maven:sonar-maven-plugin:5.1.0.4751:sonar \
                            -Dsonar.projectKey=hospital-${service} \
                            -Dsonar.host.url=http://sonarqube:9000 \
                            -Dsonar.token="\${SONAR_AUTH_TOKEN}"
                        """

                    }
                }
            }
        }
    }
}

        stage('Quality Gate') {



            steps {



                timeout(time: 10, unit: 'MINUTES') {



                    waitForQualityGate abortPipeline: true



                }


            }


        }








      stage('Build Docker Images') {

    steps {

        script {

            javaServices.each { service ->

                dir("hospital_management_app/${service}") {

                    sh """
                        echo "Building Docker image ${service}"
                        pwd
                        ls -la

                        docker build -t ${ECR_REGISTRY}/${service}:${IMAGE_TAG} .
                    """
                }
            }

            dir("hospital_management_app/${pythonService}") {

                sh """
                    echo "Building Docker image ${pythonService}"
                    pwd
                    ls -la

                    docker build -t ${ECR_REGISTRY}/${pythonService}:${IMAGE_TAG} .
                """
            }
        }
    }
}


stage('Login To AWS ECR') {

    steps {

        withCredentials([
            [$class: 'AmazonWebServicesCredentialsBinding',
             credentialsId: 'aws-creds']
        ]) {

            sh """
                aws ecr get-login-password --region ${AWS_REGION} | \
                docker login --username AWS --password-stdin ${ECR_REGISTRY}
            """
        }
    }
}


stage('Push Docker Images') {

    steps {

        script {

            javaServices.each { service ->

                sh """
                    docker push ${ECR_REGISTRY}/${service}:${IMAGE_TAG}
                """
            }

            sh """
                docker push ${ECR_REGISTRY}/${pythonService}:${IMAGE_TAG}
            """
        }
      }
   }
}
