CREATE DATABASE IF NOT EXISTS hospital_auth_db;
CREATE DATABASE IF NOT EXISTS patient_db;
CREATE DATABASE IF NOT EXISTS doctor_db;
CREATE DATABASE IF NOT EXISTS appointment_db;
CREATE DATABASE IF NOT EXISTS medical_record_db;
CREATE DATABASE IF NOT EXISTS billing_db;