pipeline {

    agent any

    parameters {

        booleanParam(
            name: 'RUN_INIT',
            defaultValue: true,
            description: 'Run Terraform Init'
        )

        booleanParam(
            name: 'RUN_VALIDATE',
            defaultValue: true,
            description: 'Run Terraform Validate'
        )

        booleanParam(
            name: 'RUN_PLAN',
            defaultValue: true,
            description: 'Run Terraform Plan'
        )

        booleanParam(
            name: 'RUN_APPLY',
            defaultValue: false,
            description: 'Run Terraform Apply'
        )

        booleanParam(
            name: 'RUN_DESTROY',
            defaultValue: false,
            description: 'Run Terraform Destroy'
        )

        booleanParam(
            name: 'CONFIRM_DESTROY',
            defaultValue: false,
            description: 'Required confirmation for Terraform Destroy'
        )
    }

    environment {

        AWS_REGION = 'ap-south-1'

    }

    stages {

        stage('Checkout Infrastructure') {

            steps {

                git(
                    branch: 'main',
                    credentialsId: 'github-creds',
                    url: 'https://github.com/kiruthigagokul/hospital-management.git'
                )

            }
        }

        stage('Verify Terraform Directory') {

            steps {

                sh '''
                    echo "===== Workspace ====="
                    pwd

                    echo "===== Terraform Directory ====="
                    ls -la hospital_management_infra/terraform

                    echo "===== Terraform Files ====="
                    find hospital_management_infra/terraform -maxdepth 1 -type f -name "*.tf" -print
                '''

            }
        }

        stage('Terraform Init') {

            when {
                expression {
                    params.RUN_INIT
                }
            }

            steps {

                dir('hospital_management_infra/terraform') {

                    sh '''
                        echo "===== Terraform Init ====="
                        terraform --version
                        terraform init
                    '''

                }

            }
        }

        stage('Terraform Validate') {

            when {
                expression {
                    params.RUN_VALIDATE
                }
            }

            steps {

                dir('hospital_management_infra/terraform') {

                    sh '''
                        echo "===== Terraform Validate ====="
                        terraform validate
                    '''

                }

            }
        }

        stage('Terraform Plan') {

            when {
                expression {
                    params.RUN_PLAN
                }
            }

            steps {

                dir('hospital_management_infra/terraform') {

                    sh '''
                        echo "===== Terraform Plan ====="
                        terraform plan -out=tfplan
                    '''

                }

            }
        }

        stage('Terraform Apply') {

            when {
                expression {
                    params.RUN_APPLY
                }
            }

            steps {

                dir('hospital_management_infra/terraform') {

                    sh '''
                        echo "===== Terraform Apply ====="
                        terraform apply -auto-approve
                    '''

                }

            }
        }

        stage('Destroy Safety Check') {

            when {
                expression {
                    params.RUN_DESTROY && !params.CONFIRM_DESTROY
                }
            }

            steps {

                error(
                    'RUN_DESTROY is enabled but CONFIRM_DESTROY is not enabled. Infrastructure was NOT destroyed.'
                )

            }
        }

        stage('Terraform Destroy') {

            when {
                expression {
                    params.RUN_DESTROY && params.CONFIRM_DESTROY
                }
            }

            steps {

                dir('hospital_management_infra/terraform') {

                    sh '''
                        echo "===== Terraform Destroy ====="
                        terraform destroy -auto-approve
                    '''

                }

            }
        }
    }

    post {

        always {

            echo "===== Infrastructure Pipeline Finished ====="

        }

    }
}
